services:
  app:
     image: caddy:2.6.2
     restart: 'no'
     networks:
      - dgraphnet
     configs:
      - source: sdconfig
        target: /usr/share/caddy/config.json
     volumes: 
      - ./site:/usr/share/caddy

  db:
    # hostname: dgraph_standalone # Hardcoded in db_init entrypoint.sh
    image: dgraph/standalone:v22.0.2
    restart: 'no'
    networks:
      - dgraphnet

  db_init:
    image: ghcr.io/sustainability-zhaw/dgraph-schema:sha-3914aa2
    restart: 'no'
    networks:
      - dgraphnet
    environment:
      TIMEOUT: 15
      DGRAPH_SERVER: http://db:8080

  db_keywords:
    image: ghcr.io/sustainability-zhaw/keywords:sha-0c40ab7
    restart: 'no'
    networks:
      - dgraphnet
    depends_on:
      db_init:
        condition: service_completed_successfully 
    environment:
      DB_URI: http://db:8080/graphql

  dspacer: 
    image: ghcr.io/sustainability-zhaw/extraction-dspace:sha-d32cad4
    restart: "no"
    networks:
      - dgraphnet
    depends_on:
      db_init:
        condition: service_completed_successfully 
    environment: 
      TARGET_HOST: https://digitalcollection.zhaw.ch
      DB_HOST: http://db:8080
      LIMIT_BATCH: 10

  adresolver: 
    image: ghcr.io/sustainability-zhaw/ad-resolver:sha-9affb17
    restart: "no"
    networks:
      - dgraphnet
    depends_on:
      db_init:
        condition: service_completed_successfully
    env_file:
      - ./contrib/ad_config.env 
      
  #Â DEV ENVIRONMENT COMPONENTS
  # These tools provide access to query browsers and the reverse proxy
  caddy:
    image: caddy:2.6.2
    restart: 'no'
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    networks:
      - dgraphnet
    ports: 
      - target: 80
        published: 8080
  
  db_browser:
    image: dgraph/ratel:v21.12.0
    restart: 'no'
    networks:
      - dgraphnet
    # ports:
    #   - '8000:8000'
  
  gql_browser: 
     image: caddy:2.6.2
     restart: 'no'
     networks:
      - dgraphnet
     volumes: 
      - ./gqldev:/usr/share/caddy

networks:
  dgraphnet:

configs:
  caddyfile:
    file: ./contrib/Caddyfile
  sdconfig:
    file: ./contrib/dashboard_config.json
